version: '3'

services:

  php-apache:
    build:
      context: ./docker/
      dockerfile: php-apache.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./web:/var/www"
    depends_on:
      - database

  database:
    image: mysql/mysql-server:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: craft
    # ports:
    #   - '3306:3306'
    volumes:
      - database_schema:/docker-entrypoint-initdb.d
      # - "${PWD}/docker-data/my.cnf:/etc/mysql/my.cnf"
      - database_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "9000:80"
  #   environment:
  #     - "PMA_ARBITRARY=1"
  #     - "PMA_HOST=database"
  #     - "PMA_USER=root"
  #     - "PMA_PASSWORD=root"
  #     - "MYSQL_ROOT_PASSWORD=root"

volumes:
  database_schema:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/db/database-schema"
  database_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/db/craft-db-data"
